Makefile
go.mod
make/deps.mk
make/ibm.mk
scripts/makefile-check/check-docker-buildx.sh
scripts/makefile-install/install-docker-buildx.sh

- Install `docker buildx` tool and check on prow that could be used to build different arch image later.
- Enable simply test case on CICD pipeline  
- https://github.com/IBM/test-infra/commit/5c6869d0e2ca5bf385ee6c74e32c8fd86cb907f5
- https://github.com/IBM/test-infra/pull/576

Set test case and tool installation check on prow

---

internal/controller/accountiam_controller.go
internal/resources/yamls/app.go
internal/resources/yamls/db_bootstrap.go
internal/resources/yamls/iam_cert_rotation.go

- Inject `Global-*` values, which are used for DB initialization, into the `database` secret.
- Remove the `create-account-iam-db` configmap from the database creation job.
- Remove the watch namespace `mcsp` hard code from the `cert-rotation` deployment and use operator namespace instead.

config MCSP and update bootstrap secret

---

internal/controller/accountiam_controller.go

remove operatorgroup length check, it might cause error when operator is installed in allnamespace mode

remove operatorgroup length check

---

internal/controller/accountiam_controller.go

Checking platform* `readyReplicas` number in deployment after restarting it.

check platform deployment ready

---

bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/accountiam_controller.go
internal/controller/util.go
internal/resources/constant.go
internal/resources/yamls/create_redis.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64340
- The user-mgmt operator created an OperandRequest requesting `ibm-redis-cp`, `ibm-websphere-liberty` and `ibm-im-operator`.
- Checked if all the requested operators are in `Running` phase.
- If the Redis CRD exists and then create a Redis CR by applying CR yaml
- If all the Operands are in `Ready` status in `ibm-user-management-request` OperandRequest
- Checked the readiness of the Redis instance.
- The operator retrieves the Redis connections info from secret

UI installation with on-prem Redis

---

bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
config/manager/manager.yaml
internal/controller/accountiam_controller.go
internal/resources/constant.go
internal/resources/yamls/im_config.go

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/64264
Three URLs added into bootstrap:
1. CP host URL
2. Account IAM base URL (Swagger UI)
3. Account IAM console URL

Add account iam console url

---

bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
config/manager/manager.yaml

**What this PR does / why we need it**:
add securityContext .ceccompProfile field to pod container
**Which issue(s) this PR fixes**:
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64465

add securityContext .seccompProfile field

---

Dockerfile
Makefile

add vcs-ref label to ibm-user-management-operator image
```
root@axe1:~/projects/go/src/ibm-user-management-operator# docker image inspect --format='{{json .Config}}' docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-scratch-docker-local/ibmcom/ibm-user-management-operator:latest | grep vcs
{"Hostname":"","Domainname":"","User":"65532:65532","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","container=oci"],"Cmd":null,"Image":"","Volumes":null,"WorkingDir":"/","Entrypoint":["/manager"],"OnBuild":null,"Labels":{"architecture":"x86_64","build-date":"2024-07-18T15:52:43","com.redhat.component":"ubi9-minimal-container","com.redhat.license_terms":"ht …
```

Operator vcs-ref

---

internal/controller/accountiam_controller.go
internal/resources/yamls/app.go

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/64554
To pick up new MCSP image: `icr.io/automation-saas-platform/access-management/account-iam:20240819135403-development-3f8f7784573adb1cc350ff25fdfc14c9b7a640f1`
Changes we made:
- Add two `CLOUD_INSTANCE_ID`, CLOUD_REGION` variables into data section in `account-iam-env-configmap-dev` (any values could be used here, `dev` is a random value we gave it)
- Remove `accoumt-iam` configMap as it is no longer used

Add new data into mcsp env configmap

---

internal/controller/accountiam_controller.go
internal/controller/utils/utils.go
internal/resources/constant.go

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/64444
New opt-out resources for users have been added: The `user-management` operator will reconcile and skip updating resources that contain the annotation `operator.ibm.com/ibm-user-management-operator.skip-update: true`

Skip updating resources

---

internal/controller/accountiam_controller.go
internal/controller/utils/utils.go
internal/resources/constant.go
internal/resources/yamls/account_iam.go
internal/resources/yamls/app.go
internal/resources/yamls/ui.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64451
- This update introduces resource hash comparison and an annotation-based skip logic to the reconciliation process, allowing the operator to avoid unnecessary updates by comparing configuration hashes and skip-update annotation.
- Remove all the argocd annotation from the yaml templates

Implement resource hash comparison logic in reconciliation

---

internal/controller/accountiam_controller.go
internal/controller/utils/utils.go

Fix for a bunch of secrets issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64217
Enhancement ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64451
- Introduced a hash-based comparison to determine whether updates are needed. 
- For Jobs, if changes are detected, the resource is deleted and recreated. 
- For non-Job resources, the template is merged with the existing resource if the hashes match, ensuring new fields are added without overwriting unchanged ones. If the hashes don't match, the resource is overwritten by the template. 
- Implemented a solution for deep merging resources, including metadata and spec, by using the `mergeResources` function.

[MCSP] hash comparison and deep merge all the resources

---

internal/controller/accountiam_controller.go
internal/resources/constant.go
internal/resources/yamls/account_iam.go
internal/resources/yamls/create_redis.go
internal/resources/yamls/ui.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64767
This update consolidates the certificate management for the `user-managment` operator and its dependencies by replacing multiple self-signed certificates with a certificate chain.

Update certificate chain for user-mgmt operator and services

---

cmd/main.go
go.mod
go.sum
internal/controller/accountiam_controller.go
internal/controller/utils/utils.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64443
Ensure that whenever one of the owned resources (Deployment, Secret, ConfigMap ...) is modified or deleted, the controller will automatically reconcile the associated AccountIAM CR.

Watch all resources owned by AccountIAM CR

---

internal/controller/accountiam_controller.go
internal/resources/constant.go
internal/resources/yamls/app.go
internal/resources/yamls/im_config.go
internal/resources/yamls/im_integration.go

Ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64687
1. The `user-mgmt-operator` will create a new secret named `mcsp-im-integration-details` to store all IM integration values.
2. Apply the job `mcsp-im-config-job` using all the references from the above secret.
3. Generate encryption key for account IAM and save it in `account-iam-database-secret` secret
- Test image: quay.io/yuchen_shen/ibm-user-management-operator:integration_secret
- Update IM job image in CSV with: docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-scratch-docker-local/ibmcom/mcsp-im-config-job-amd64:c47ff7e

Creating IM job by using the values from integration secret

---

go.mod
internal/resources/yamls/account_iam.go
internal/resources/yamls/app.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65280
Add `TOKEN_EXCHANGE_VALIDATE_ROLES` value into the `account-iam-env-configmap-development` configmap and set it as `true` as default
test image: quay.io/yuchen_shen/ibm-user-management-operator:dev

update account iam env development configmap

---

internal/resources/yamls/app.go

https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66240
account iam application was not starting with the latest account-iam image because the notification flag in the account-iam-env-configmap-development configmap needed a value and could no longer be empty string.  Setting to false.

fix flag to allow account iam application to start with new image

---

internal/controller/accountiam_controller.go
internal/resources/constant.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66518
What is the PR for:
To avoids the encryption keys conflict error by ensuring the keys are not regenerated during each reconciliation
How to test:
1. test image: `quay.io/yuchen_shen/ibm-user-management-operator:encrption_key`
2. After installing user management, delete the pod and see if the `ENCRYPTION_KEYS` in `account-iam-database-secret` is still regenerated and `account-iam-db-migration-mcspid` job is kept failed (they should not)

Avoid the encryption keys conflict error

---

internal/controller/accountiam_controller.go

Added `json` struct tags to the `BootstrapSecret` type.
These tags are used during the unmarshalling of Kubernetes secret data into the `BootstrapData` global variable, ensuring correct mapping of secret keys to struct fields. 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64451
Test image: quay.io/yuchen_shen/ibm-user-management-operator:json
Install UM; all services work properly

Serialize BootstrapSecret structs to JSON

---

internal/controller/accountiam_controller.go

Description: Redis CR version 1.2.0 is not supported by Redis 1.2.8 operator, update the version to the latest `1.2.8` to avoid the error:
```
fatal: [localhost]: FAILED! => {"changed": false, "reason": "the role 'rediscp_1.2.0' was not found in /opt/ansible/roles:/opt/ansible/roles:/opt/ansible"}
```
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66170

Update Redis CR version to 1.2.8

---

client/account_iam/client.go

because these do not necessarily exist when operator is installed

removed empty base url and api key error

---

internal/controller/accountiam_controller_test.go
internal/controller/suite_test.go
internal/controller/testutils/slice_utils.go
internal/controller/testutils/slice_utils_test.go

Adds a full test suite for the AccountIAM controller, covering all parts of the reconciliation process and related infrastructure
1. Complete Test Infrastructure `suite_test.go`
- Kube Test Env Sets up realistic test environment using envtest
- Schema Registration: Registers all required API types (AccountIAM, ConfigMaps, Secrets, RBAC)
- Environment Management: Handles setup/teardown of test Kubernetes API server
2. Comprehensive Controller Tests `accountiam_controller_test.go`
Implements 6-phase testing approach that mirrors the controller's reconciliation logic:
- Phase 1: Resource Validation
- Phase 2: Prerequisites Verification
- Phase 3: Resource Management
- Phase 4: Status Management
- Phase 5: Error Scenarios
3. Utility Function Testing
-  Tests `contains()` helper function for …

[UM] Add AccountIAM controller test suits
